### ISSUE TITLE
Занятие 3

### ISSUE THREAD

**Issue by dsokolov** [AltarixExercises2016/Semenov.Matvey#2]
1. Классы следует именовать с большой буквы, на зависимо от того, внутренние они нет.
Т.е. вместо
```java
class lookThread extends Thread {
```
следует писать
```java
class LookThread extends Thread {
```
и тд

2. Не забывай про отступы и прочее форматирование. В идее и студии для этого есть хоткей ctrl+alt+L

3. Попробуй сделать так, чтобы:
- WriteThread работал пока программа не будет остановлена.
- LookThread работал пока есть элементы в country. Когда закончатся - останавливал программу.
- LookThread убирал элементы из country.
- Время задержки для обоих потоков каждый раз бралось случайное.

**Comment by matek3022** [comment]
все сделал, кроме пункта "Когда закончатся - останавливал программу."
как закончить работу программы когда выскакивает исключение? у меня завершается только поток в котором вызывается это исключение

**Comment by dsokolov** [comment]
Можно завести флаг
```java
static boolean working = true
```
Внутри потоков цикл `while(working){...}`. Когда нужно завершить, делаем `working = false`.
Чтобы эксепшена не было, нужно делать соответствующую проверку.

**Comment by matek3022** [comment]
готово) сейчас запушу

**Comment by matek3022** [comment]
запушил

**Comment by dsokolov** [comment]
Всё ок.
