### ISSUE TITLE
Какое приложение разрабатываем?

### ISSUE THREAD

**Issue by dsokolov** [AltarixExercises2016/Semenov.Matvey#3]
Либо AltarixAppFirst, либо VKMessager - непонятно что мне смотреть.
Определись и лишнее удали.

**Comment by matek3022** [comment]
я создал AltarixAppFirst для домашнего задания, а VKMessager просто добавил в начале курса

**Comment by dsokolov** [comment]
Ничего же не мешает делать домашку в VKMessager, задания такие абстрактные, что их можно применить к любому приложению.

**Comment by matek3022** [comment]
да, я согласен, не подумал, поправлю :)

**Comment by matek3022** [comment]
удалил лишнее, добавил базу данных в DialogsActivity

**Comment by matek3022** [comment]
при вызове onPause() обновляется база данных

**Comment by dsokolov** [comment]
Ok!
